-- =====================================================================
-- AI Future Process Designer — baseline schema
--
-- Design notes:
--  * UUID primary keys are generated by the application (Hibernate), not
--    by the database, so the schema stays portable across Postgres hosts
--    (Neon / Supabase / local) with no extension requirements.
--  * The CURRENT state lives in: process, activity, problem, role,
--    system_tool and their join tables.
--  * The TRANSITION reasoning layer is ai_opportunity (+ its evidence links).
--  * The FUTURE state lives in: future_activity, ai_intervention.
--  * Every AI-generated row is deletable/regenerable per process so that
--    POST /api/processes/{id}/analyze is idempotent.
-- =====================================================================

CREATE TABLE process (
    id                UUID PRIMARY KEY,
    name              VARCHAR(200) NOT NULL,
    industry          VARCHAR(120) NOT NULL,
    description       TEXT         NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    origin            VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    last_analyzed_at  TIMESTAMPTZ,
    CONSTRAINT ck_process_status CHECK (status IN ('CURRENT_ONLY', 'ANALYZED')),
    CONSTRAINT ck_process_origin CHECK (origin IN ('SEED', 'USER'))
);

CREATE INDEX idx_process_status ON process (status);
CREATE INDEX idx_process_created_at ON process (created_at DESC);

-- ---------------------------------------------------------------------
-- CURRENT STATE
-- ---------------------------------------------------------------------

CREATE TABLE activity (
    id              UUID PRIMARY KEY,
    process_id      UUID         NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    sequence_order  INTEGER      NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_activity_sequence CHECK (sequence_order >= 0)
);

CREATE INDEX idx_activity_process ON activity (process_id, sequence_order);

CREATE TABLE role (
    id          UUID PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE system_tool (
    id          UUID PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    type        VARCHAR(80)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_system_tool_name UNIQUE (name)
);

CREATE TABLE activity_role (
    activity_id UUID NOT NULL REFERENCES activity (id) ON DELETE CASCADE,
    role_id     UUID NOT NULL REFERENCES role (id) ON DELETE CASCADE,
    PRIMARY KEY (activity_id, role_id)
);

CREATE TABLE activity_system (
    activity_id UUID NOT NULL REFERENCES activity (id) ON DELETE CASCADE,
    system_id   UUID NOT NULL REFERENCES system_tool (id) ON DELETE CASCADE,
    PRIMARY KEY (activity_id, system_id)
);

CREATE TABLE problem (
    id           UUID PRIMARY KEY,
    process_id   UUID        NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    activity_id  UUID        REFERENCES activity (id) ON DELETE SET NULL,
    description  TEXT        NOT NULL,
    severity     VARCHAR(10) NOT NULL,
    source       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_problem_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_problem_source CHECK (source IN ('SEED', 'AI_GENERATED'))
);

CREATE INDEX idx_problem_process ON problem (process_id);
CREATE INDEX idx_problem_activity ON problem (activity_id);

-- ---------------------------------------------------------------------
-- KNOWLEDGE / EVIDENCE LAYER
-- ---------------------------------------------------------------------

CREATE TABLE knowledge_snippet (
    id            UUID PRIMARY KEY,
    title         VARCHAR(250) NOT NULL,
    snippet_text  TEXT         NOT NULL,
    source_url    VARCHAR(600) NOT NULL,
    source_type   VARCHAR(20)  NOT NULL,
    publisher     VARCHAR(200),
    tags          VARCHAR(400) NOT NULL DEFAULT '',
    retrieved_at  DATE         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_knowledge_snippet_title UNIQUE (title),
    CONSTRAINT ck_knowledge_snippet_source_type CHECK (
        source_type IN ('LAW', 'GUIDANCE', 'STANDARD', 'RESEARCH', 'VENDOR', 'GENERAL_WEB')
    )
);

-- ---------------------------------------------------------------------
-- TRANSITION LAYER (AI reasoning)
-- ---------------------------------------------------------------------

CREATE TABLE ai_opportunity (
    id                    UUID        PRIMARY KEY,
    process_id            UUID        NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    activity_id           UUID        REFERENCES activity (id) ON DELETE SET NULL,
    description           TEXT        NOT NULL,
    ai_capability         VARCHAR(250) NOT NULL,
    automation_potential  VARCHAR(10) NOT NULL,
    business_benefit      TEXT,
    risk                  TEXT,
    reasoning_note        TEXT,
    display_order         INTEGER     NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_ai_opportunity_potential CHECK (automation_potential IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX idx_ai_opportunity_process ON ai_opportunity (process_id, display_order);
CREATE INDEX idx_ai_opportunity_activity ON ai_opportunity (activity_id);

CREATE TABLE ai_opportunity_evidence (
    ai_opportunity_id     UUID NOT NULL REFERENCES ai_opportunity (id) ON DELETE CASCADE,
    knowledge_snippet_id  UUID NOT NULL REFERENCES knowledge_snippet (id) ON DELETE CASCADE,
    PRIMARY KEY (ai_opportunity_id, knowledge_snippet_id)
);

-- ---------------------------------------------------------------------
-- FUTURE STATE
-- ---------------------------------------------------------------------

CREATE TABLE future_activity (
    id                      UUID         PRIMARY KEY,
    process_id              UUID         NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    name                    VARCHAR(250) NOT NULL,
    sequence_order          INTEGER      NOT NULL,
    description             TEXT,
    human_responsibility    TEXT,
    ai_responsibility       TEXT,
    responsibility_type     VARCHAR(20)  NOT NULL,
    created_at              TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_future_activity_resp_type CHECK (
        responsibility_type IN ('AI_AUTOMATED', 'AI_AUGMENTED', 'HUMAN_LED')
    ),
    CONSTRAINT ck_future_activity_sequence CHECK (sequence_order >= 0)
);

CREATE INDEX idx_future_activity_process ON future_activity (process_id, sequence_order);

CREATE TABLE ai_intervention (
    id                        UUID        PRIMARY KEY,
    process_id                UUID        NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    future_activity_id        UUID        REFERENCES future_activity (id) ON DELETE CASCADE,
    related_ai_opportunity_id UUID        REFERENCES ai_opportunity (id) ON DELETE SET NULL,
    intervention_type         VARCHAR(15) NOT NULL,
    description               TEXT        NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_ai_intervention_type CHECK (
        intervention_type IN ('AUTOMATE', 'AUGMENT', 'ELIMINATE', 'NEW')
    )
);

CREATE INDEX idx_ai_intervention_process ON ai_intervention (process_id);
CREATE INDEX idx_ai_intervention_future_activity ON ai_intervention (future_activity_id);

-- ---------------------------------------------------------------------
-- TRACEABILITY: one row per execution of the analysis pipeline
-- ---------------------------------------------------------------------

CREATE TABLE analysis_run (
    id                   UUID        PRIMARY KEY,
    process_id           UUID        NOT NULL REFERENCES process (id) ON DELETE CASCADE,
    status               VARCHAR(15) NOT NULL,
    provider             VARCHAR(60) NOT NULL,
    model                VARCHAR(120) NOT NULL,
    prompt_text          TEXT,
    raw_response         TEXT,
    repair_attempted     BOOLEAN     NOT NULL DEFAULT FALSE,
    validation_warnings  TEXT,
    error_message        TEXT,
    prompt_tokens        INTEGER,
    output_tokens        INTEGER,
    duration_ms          BIGINT,
    started_at           TIMESTAMPTZ NOT NULL,
    finished_at          TIMESTAMPTZ,
    CONSTRAINT ck_analysis_run_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX idx_analysis_run_process ON analysis_run (process_id, started_at DESC);

-- Which curated snippets were retrieved for a given run, and with what score.
CREATE TABLE analysis_run_snippet (
    analysis_run_id      UUID             NOT NULL REFERENCES analysis_run (id) ON DELETE CASCADE,
    knowledge_snippet_id UUID             NOT NULL REFERENCES knowledge_snippet (id) ON DELETE CASCADE,
    relevance_score      DOUBLE PRECISION NOT NULL,
    matched_terms        VARCHAR(500),
    PRIMARY KEY (analysis_run_id, knowledge_snippet_id)
);
